// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVng2DpZb1AH-SJhvGxALs5paCYzy6E4M',
    appId: '1:982101680729:web:88b7fb192d5d965677c748',
    messagingSenderId: '982101680729',
    projectId: 'emindsapp',
    authDomain: 'emindsapp.firebaseapp.com',
    storageBucket: 'emindsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcnR86BI19018SGLnH0grNGcHi_8XeLNE',
    appId: '1:982101680729:android:b11544865033dbee77c748',
    messagingSenderId: '982101680729',
    projectId: 'emindsapp',
    storageBucket: 'emindsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRiJH17qTdBFk3KOV-N4pgqXGEQ5K0vo',
    appId: '1:982101680729:ios:ac42be0d4bf2995b77c748',
    messagingSenderId: '982101680729',
    projectId: 'emindsapp',
    storageBucket: 'emindsapp.appspot.com',
    iosClientId: '982101680729-jmjep562bp2ach6rjd7ve58qp82k5lk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.emindsApp',
  );
}
